[project]
name = "day2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "groq>=1.6.0",
    "numpy>=2.5.2",
    "python-dotenv>=1.2.3",
    "sentence-transformers>=6.0.0",
]

[project.scripts]
day2 = "day2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
